---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Monitoring:
    - Grafana:
        icon: grafana.svg
        href: http://monitoring.game.anonymus09.com:3002/
        description: Data visualization
        widget:
          type: grafana
          url: http://monitoring.game.anonymus09.com:3002
          username: admin
          password: Admin123
    - Prometheus:
        icon: prometheus.svg
        href: http://monitoring.game.anonymus09.com:9090/
        description: Metrics server.
        widget:
          type: prometheus
          url: http://monitoring.game.anonymus09.com:9090
    - Gatus:
        icon: gatus.svg
        href: http://monitoring.game.anonymus09.com:8080/
        description: Uptime monitoring tool.
        widget:
          type: gatus
          url: http://monitoring.game.anonymus09.com:8080

- Development:
    - pgAdmin 4:
        icon: pgadmin.svg
        href: http://srv.gmae.anonymus09.com:8888/
        description: Postgres DB management dashboard.
    - S3 assets:
        icon: minio.svg
        href: http://srv.game.anonymus09.com:9001/
        description: S3 asset storage.
    - S3 docker cache:
        icon: minio.svg
        href: http://srv.game.anonymus09.com:9001/
        description: S3 docker cache storage.
    - Gitea:
        icon: gitea.svg
        href: https://gitea.home.anonymus09.com/
        description: local git repo
