networks:
  monitoring:

volumes:
  grafana_data:
  prometheus_data:
  homepage_data:

services:
  ###Â PROMETHEUS ###
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      monitoring:
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/config/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/config/prometheus.yml"
  ### GRAFANA ###
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      monitoring:
    ports:
      - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER="admin"
      - GF_SECURITY_ADMIN_PASSWORD="Admin123"

  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config/gatus.yml:/config/config.yaml

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 80:3000
    volumes:
      - ./homepage/docker.yaml:/app/config/docker.yaml:ro
      - ./homepage/services.yaml:/app/config/services.yaml:ro
      - ./homepage/settings.yaml:/app/config/setting.yaml:ro
      - ./homepage/widgets.yaml:/app/config/widgets.yaml:ro
      - ./homepage/bookmarks.yaml:/app/config/bookmarks.yaml:ro
      - homepage_data:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=monitoring.game.anonymus09.com
